swagger: "2.0"

info:
  title: "AlphaCar Credit Inquiry API"
  version: "1.0"

consumes:
  - application/json
produces:
  - application/json

basePath: /aci_api

paths:
  /index:
    get:
      tags: [INDEX]
      summary: basic info of alphacar
      description: basic info of alphacar
      produces:
        - text/plain
      responses:
        200:
          description: basic info of alphacar response
          schema:
            type: string

  /greeting/{name}:
    get:
      tags: [INDEX]
      summary: Generate greeting
      description: Generates a greeting message.
      produces:
        - text/plain
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John. This is AlphaCar.IO."

  /creditinquiry/latest:
    get:
      tags: [Credit Inquiry]
      summary: get latest Credit Inquiry
      description: get latest Credit Inquiry
      produces:
        - application/json
      responses:
        200:
          description: infos response
          schema:
            $ref: "#/definitions/CreditInquiryResult"

  /creditinquiry/hash/{hash}:
    get:
      tags: [Credit Inquiry]
      summary: get Credit Inquiry
      description: get credit inquiry by hash
      produces:
        - application/json
      parameters:
        - name: hash
          in: path
          description: the hash string.
          required: true
          type: string
      responses:
        200:
          description: infos response
          schema:
            $ref: "#/definitions/CreditInquiryResult"

  /creditinquiry/classification:
    get:
      tags: [Credit Inquiry]
      summary: get credit inquiry list by classification
      description: get credit inquiry list by classification
      produces:
        - application/json
      responses:
        200:
          description: CreditInquiry List response
          schema:
            $ref: "#/definitions/GroupItemListResult"

  /creditinquiry/list:
    get:
      tags: [Credit Inquiry]
      summary: get credit inquiry by conditions
      description: get credit inquiry by conditions
      produces:
        - application/json
      parameters:
        - name: search_type
          in: query
          description: the search_type string.
          required: false
          type: string
        - name: search_txt
          in: query
          description: the search_txt string.
          required: false
          type: string
        - name: page_size
          in: query
          description: the page size.
          required: false
          type: "integer"
          format: "int32"
        - name: page
          in: query
          description: the page num.
          required: false
          type: "integer"
          format: "int32"
      responses:
        200:
          description: CreditInquiry List response
          schema:
            $ref: "#/definitions/CreditInquiryListResult"

  /creditinquiry/tx_count_lst:
    post:
      tags: [Credit Inquiry]
      summary: get tx count list
      description: get tx count list
      produces:
        - application/json
      parameters:
        - name: dates
          in: body
          description: the dates list.
          required: true
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        200:
          description: tx count list response
          schema:
            $ref: "#/definitions/TxCountListResult"

  /rewardrecord/latest:
    get:
      tags: [Reward Record]
      summary: get latest Reward Record
      description: get latest Reward Record
      produces:
        - application/json
      responses:
        200:
          description: infos response
          schema:
            $ref: "#/definitions/RewardRecordResult"

  /rewardrecord/list:
    get:
      tags: [Reward Record]
      summary: get Reward Record by conditions
      description: get Reward Record by conditions
      produces:
        - application/json
      parameters:
        - name: activity_type
          in: query
          description: the activity_type string.
          required: true
          type: string
        - name: page_size
          in: query
          description: the page size.
          required: false
          type: "integer"
          format: "int32"
        - name: page
          in: query
          description: the page num.
          required: false
          type: "integer"
          format: "int32"
      responses:
        200:
          description: CreditInquiry List response
          schema:
            $ref: "#/definitions/CreditInquiryListResult"

definitions:

  RewardRecord:
    type: "object"
    properties:
      create_Time:
        type: "string"
        format: "date-time"
        pattern: "yyyy-MM-ddTHH:mm:ss.ZZZ"
        example: "2019-03-25T16:00:00.000Z"
      activityType:
        type: "string"
      issueNumber:
        type: "integer"
        format: "int32"
      ranking:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      account:
        type: "string"
      reward:
        type: "string"
      comments:
        type: "string"
      record_Time:
        type: "string"
        format: "date-time"
        pattern: "yyyy-MM-ddTHH:mm:ss.ZZZ"
        example: "2019-03-25T16:00:00.000Z"
      hash:
        type: "string"
      txId:
        type: "string"

  RewardRecordResult:
    type: "object"
    properties:
      error_code:
        type: "integer"
        format: "int32"
      error_msg:
        type: "string"
      data:
        $ref: "#/definitions/RewardRecord"

  CreditInquiry:
    type: "object"
    properties:
      create_Time:
        type: "string"
        format: "date-time"
        pattern: "yyyy-MM-ddTHH:mm:ss.ZZZ"
        example: "2019-03-25T16:00:00.000Z"
      account:
        type: "string"
      name:
        type: "string"
      personId:
        type: "string"
      comments:
        type: "string"
      register_Time:
        type: "string"
        format: "date-time"
        pattern: "yyyy-MM-ddTHH:mm:ss.ZZZ"
        example: "2019-03-25T16:00:00.000Z"
      reason:
        type: "string"
      record_Time:
        type: "string"
        format: "date-time"
        pattern: "yyyy-MM-ddTHH:mm:ss.ZZZ"
        example: "2019-03-25T16:00:00.000Z"
      money:
        type: "string"
      hash:
        type: "string"
      txId:
        type: "string"

  CreditInquiryResult:
    type: "object"
    properties:
      error_code:
        type: "integer"
        format: "int32"
      error_msg:
        type: "string"
      data:
        $ref: "#/definitions/CreditInquiry"

  CreditInquiryListResult:
    type: "object"
    properties:
      error_code:
        type: "integer"
        format: "int32"
      error_msg:
        type: "string"
      data:
        type: "object"
        properties:
          total_count:
            type: "integer"
            format: "int32"
          lst:
            type: "array"
            items:
              $ref: "#/definitions/CreditInquiry"

  TxCount:
    type: "object"
    properties:
      date_str:
        type: "string"
      count:
        type: "integer"
        format: "int32"

  TxCountListResult:
    type: "object"
    properties:
      error_code:
        type: "integer"
        format: "int32"
      error_msg:
        type: "string"
      data:
        type: "object"
        properties:
          lst:
            type: "array"
            items:
              type: "integer"
              format: "int32"

  GroupItem:
    type: "object"
    properties:
      _id:
        type: "string"
      count:
        type: "integer"
        format: "int32"

  GroupItemListResult:
    type: "object"
    properties:
      error_code:
        type: "integer"
        format: "int32"
      error_msg:
        type: "string"
      data:
        type: "object"
        properties:
          lst:
            type: "array"
            items:
              $ref: "#/definitions/GroupItem"
